version: '2'
catalog:
  name: "BNB Service Healthchecks"
  version: "v0.0.6"
  description: "A Sinatra Based App for Monitoring Services within Rancher"
  questions: 
    - variable: host_label
      label: "Host with Label to put healthchecker on"
      description: |
        Host label to use as healthcheck 'value' tag.
        Example: 'healthchecker=true'
      required: false
      type: "string"  
    - variable: url_namespace
      label: "URL Namespace"
      description: "secure/healthchecks"
      required: false
      type: "string" 
    - variable: postgresql_database_service
      label: "PostgreSQL Database Service"
      description: "PostgreSQL"
      required: false
      type: service
    - variable: postgresql_database
      label: "PostgreSQL Database Name"
      description: "i.e. myapp_production"
      required: false
      type: "string" 
    - variable: postgresql_username
      label: "PostgreSQL Username"
      required: false
      type: "string" 
    - variable: postgresql_password
      label: "PostgreSQL Password"
      required: false
      type: "string" 
    - variable: postgresql_port
      label: "PostgreSQL Port"
      required: false
      type: "string"
      default: '5432'
    - variable: mysql_database_service
      label: "MySQL Database Service"
      description: "MySQL"
      required: false
      type: service
    - variable: mysql_database
      label: "MySQL Database Name"
      description: "i.e. myapp_production"
      required: false
      type: "string" 
    - variable: mysql_username
      label: "MySQL Username"
      required: false
      type: "string" 
    - variable: mysql_password
      label: "MySQL Password"
      required: false
      type: "string" 
    - variable: mysql_port
      label: "MySQL Port"
      required: false
      type: "string"
      default: '3306'

services:
  service-healthchecks:
    scale: 1
