version: '2'
catalog:
  name: "BNB Service Healthchecks"
  version: "v0.0.2"
  description: "A Sinatra Based App for Monitoring Services within Rancher"
  questions:       
    - variable: postgres_database_service
      label: "PostgreSQL Database Service"
      description: "PostgreSQL"
      required: false
      type: service
    - variable: postgresql_database
      label: "PostgreSQL Database Name"
      description: "i.e. myapp_production"
      required: false
      type: "string" 
    - variable: postgresql_username
      label: "PostgreSQL Username"
      required: false
      type: "string" 
    - variable: postgresql_password
      label: "PostgreSQL Password"
      required: false
      type: "string" 
    - variable: postgresql_port
      label: "PostgreSQL Port"
      required: false
      type: "string" 

    - variable: host_label
      label: "Host with Label to put healthchecker on"
      description: |
        Host label to use as healthcheck 'value' tag.
        Example: 'healthchecker=true'
      required: false
      type: "string"

services:
  service-healthchecks:
    scale: 1
