version: '2'

services:

  elasticsearch:
    restart: always
    image: opticbob/elk_elasticsearch:latest
    environment:
      ES_JAVA_OPTS: "-Xmx${heap_size}m -Xms${heap_size}m"
    networks:
      - elk

  logstash:
    restart: always
    image: opticbob/elk_logstash:latest
    environment:
      LS_JAVA_OPTS: "-Xmx${heap_size}m -Xms${heap_size}m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    restart: always
    image: opticbob/elk_kibana:latest
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
