version: '2'
catalog:
  name: "REX-Ray DigitalOcean"
  version: "v0.0.2"
  description: "Docker volume plugin for DigitalOcean"
  questions:
    - variable: DOBS_TOKEN
      type: string
      required: true
      label: DigitalOcean Token
      description: DigitalOcean access token
    - variable: DEFAULT_VOLUME_SIZE
      type: int
      required: true
      default: 1
      label: DigitalOcean default volume size
      description: Size in GB to create volumes in DigitalOcean
    - variable: RANCHER_DEBUG
      type: enum
      required: true
      default: false
      options:
      - true
      - false
      label: Debug Mode
      description: Enable or disable verbose logging
    - variable: host_label
      label: "Host with Label to put REX-Ray on"
      description: |
        Host label to use as REX-ray 'value' tag.
        Example: 'database=true'
      required: false
      default: ""
      type: "string"
services:
  rexray-dobs:
    scale: 1

# bnb-rexray-dobs-driver:
#   storage_driver:
#     name: rexray-dobs
#     scope: environment
#     volume_access_mode: singleHostRW
